kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage-class"
spec:
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Mi
